DISCOVERY_ANALYSIS = """
Given a the discovery sales call transcript between {buyer} and {seller}, you need to identify the following key elements about the {buyer}'s data for the {stakeholder} of {buyer} present in the call -\n"
1. {buyer} 's Pain Points - The pain points expressed by the buyer during the call.\n"
2. {buyer} 's Objections - The objections raised by the buyer during the call.\n"
3. {buyer} 's Time Lines - The time lines mentioned by the buyer during the call.\n"
4. {buyer} 's Success Indicators - The success indicators mentioend by the buyer during the call.\n"
5. {buyer} 's Budget Constraints - The budget constraints expressed by the buyer during the call.\n"
6. {buyer} 's Decision Committee - The members of the decision mentioned by the buyer during the call.\n"
7. {buyer} 's Competition - The competitors mentioned by the buyer during the call.\n"
If there is no information about any of the above points, you should provide response as - No information found. "
The goal is to provide insights to the sales team for improving future calls and addressing the buyer's needs effectively and also to prepare for the discovery call."
The discovery call transcript:\n{discovery_transcript}\n"
"""